// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef etip_h
#define etip_h
#include <efltk/Fl.h>
#include <efltk/Fl_Locale.h>
#include <efltk/Fl_Window.h>
#include <efltk/Fl_Box.h>
#include <efltk/Fl_Check_Button.h>
extern Fl_Check_Button* show_check;
#include <efltk/Fl_Group.h>
extern Fl_Box* tipsBox;
#include <efltk/Fl_Button.h>
#endif
