// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef erun_h
#define erun_h
#include <efltk/Fl.h>
#include <efltk/Fl_Locale.h>
#include <efltk/Fl_Window.h>
extern Fl_Window* windowRunDialog;
#include <efltk/Fl_Input.h>
extern Fl_Input* inputRunDialog;
#include <efltk/Fl_Box.h>
#include <efltk/Fl_Button.h>
void run_resource(char *cmd);
#endif
