// generated by Extended Fast Light User Interface Designer (eFluid) version 2.0003

#include "propdialog.h"

int main (int argc, char **argv) {

	Fl_Window* w;
	
	{
Fl_Window* o = new Fl_Window(310, 290, _("Icon settings"));
		w = o;
		o->shortcut(0xff1b);
		new Fl_Button(225, 260, 80, 25, _("&Close"));
		new Fl_Button(140, 260, 80, 25, _("&Apply"));
		
		{
Fl_Tabs* o = new Fl_Tabs(5, 5, 300, 249);
			o->color((Fl_Color)0xfffffffe);
			
			{
Fl_Group* o = new Fl_Group(1, 23, 298, 225, _("Settings"));
				new Fl_Box(129, 10, 60, 60, _("label"));
				
				{
Fl_Input* o = new Fl_Input(9, 88, 250, 25, _("Name:"));
					o->align(FL_ALIGN_TOP|FL_ALIGN_LEFT);
				}
				
				{
Fl_Input* o = new Fl_Input(9, 133, 250, 25, _("Image:"));
					o->align(FL_ALIGN_TOP|FL_ALIGN_LEFT);
				}
				
				{
Fl_Button* o = new Fl_Button(264, 133, 25, 25, _("..."));
					o->label_type(FL_ENGRAVED_LABEL);
					/*image browse button*/
				}
				
				{
Fl_Input* o = new Fl_Input(9, 188, 250, 25, _("Program to run:"));
					o->align(FL_ALIGN_TOP|FL_ALIGN_LEFT);
				}
				
				{
Fl_Button* o = new Fl_Button(264, 188, 25, 25, _("..."));
					o->label_type(FL_ENGRAVED_LABEL);
					/*program cmd button*/
				}
				o->end();
			}
			
			{
Fl_Group* o = new Fl_Group(1, 23, 298, 225, _("Terminal"));
				o->hide();
				new Fl_Check_Button(9, 18, 250, 25, _("Run in terminal"));
				
				{
Fl_Input* o = new Fl_Input(9, 68, 250, 25, _("Terminal program:"));
					o->align(FL_ALIGN_TOP|FL_ALIGN_LEFT);
				}
				
				{
Fl_Button* o = new Fl_Button(264, 68, 26, 25, _("..."));
					o->label_type(FL_ENGRAVED_LABEL);
				}
				o->end();
			}
			o->end();
		}
		o->end();
		o->resizable(o);
	}
	w->show(argc, argv);
	return  Fl::run();
}
