// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "demo.h"
#include "Panel.h"

int main(int argc, char **argv) {
  Panel* w;
  { Panel* o = new Panel(475, 75);
    w = o;
    { new Fl_Button(185, 25, 90, 25, "button 2");
    } // Fl_Button* o
    { new Fl_Button(85, 25, 90, 25, "button 1");
    } // Fl_Button* o
    o->end();
  } // Panel* o
  w->show(argc, argv);
  return Fl::run();
}
