// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef ecolorconf_h
#define ecolorconf_h
#include <efltk/Fl.h>
#include <efltk/Fl_Locale.h>
#include <efltk/Fl_Window.h>
extern Fl_Window* windowColorSettings;
#include <efltk/Fl_Tabs.h>
#include <efltk/Fl_Group.h>
#include <efltk/Fl_Button.h>
extern void ChangeBoxColor(Fl_Button*, void*);
extern Fl_Button* colorBox;
extern Fl_Button* labelColorBox;
extern Fl_Button* selectionColorBox;
extern Fl_Button* selectionTextColorBox;
extern Fl_Button* offColorBox;
extern Fl_Button* highlightColorBox;
extern Fl_Button* highlightLabelColorBox;
extern Fl_Button* textColorBox;
extern Fl_Button* backgroundBox;
extern Fl_Button* textBackgroundBox;
extern Fl_Button* tooltipBox;
extern Fl_Button* tooltipTextColorButton;
#include <efltk/Fl_Check_Button.h>
extern Fl_Check_Button* tooltipsEnableEffects;
extern Fl_Check_Button* tooltipsEnable;
#include <efltk/Fl_Choice.h>
extern Fl_Choice* tooltipsEffectType;
#include <efltk/Fl_Item.h>
#include <efltk/Fl_Value_Input.h>
extern Fl_Value_Input* tooltipsDelay;
#include <efltk/Fl_Input_Browser.h>
extern Fl_Input* labelFontInput;
extern Fl_Input* textFontInput;
extern Fl_Input_Browser* labelSize;
extern Fl_Input_Browser* textSize;
extern Fl_Input_Browser* fontEncoding;
extern Fl_String fl_font_dialog();
extern Fl_Check_Button* menusEnableEffects;
extern Fl_Check_Button* menusEnableSubwindowEffects;
extern Fl_Choice* menusEffectType;
extern Fl_Value_Input* menusSpeed;
extern Fl_Value_Input* menusDelay;
extern Fl_Check_Button* mdiAnimation;
extern Fl_Check_Button* mdiOpaqueAnimation;
extern Fl_Check_Button* imagesStateEffect;
extern Fl_Check_Button* allApplyRadioButton;
extern Fl_Input_Browser* schemeListBox;
void ChangeBoxColor(Fl_Button *box, void *);
#endif
