// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef etimedate_h
#define etimedate_h
#include <efltk/Fl.h>
#include <efltk/Fl_Locale.h>
#include <efltk/Fl_Window.h>
#include <efltk/Fl_Group.h>
#include <efltk/Fl_Button.h>
#include <efltk/Fl_Tabs.h>
#include <efltk/Fl_Calendar.h>
#include <efltk/Fl_Clock.h>
#include "fl_time.h"
extern Fl_Time* timeBox;
#include <efltk/Fl_Box.h>
#include <efltk/Fl_Input_Browser.h>
extern Fl_Input_Browser* timeZonesList;
#endif
