#
# $Id$
#
# Part of Equinox Desktop Environment (EDE).
# Copyright (c) 2000-2006 EDE Authors.
#
# This program is licenced under terms of the 
# GNU General Public Licence version 2 or newer.
# See COPYING for details.

CPPFILES = aboutdialog.cpp
TARGET   =


POFILES = locale/de.po locale/fr.po

include ../makeinclude

all: aboutdialog.o

install:

uninstall:

clean:
	$(RM) *.o

