// generated by Extended Fast Light User Interface Designer (eFluid) version 2.0003

#ifndef _PROPDIALOG_H_
#define _PROPDIALOG_H_

#include <efltk/Fl.h>
#include <efltk/Fl_Locale.h>
#include <efltk/Fl_Window.h>
#include <efltk/Fl_Button.h>
#include <efltk/Fl_Tabs.h>
#include <efltk/Fl_Group.h>
#include <efltk/Fl_Box.h>
#include <efltk/Fl_Input.h>
#include <efltk/Fl_Check_Button.h>


#endif
